apiVersion: 3
provenanceSpec:
  corpus: Inscriptions of Israel/Palestine (IIP)
  org: alexsosn
  repo: IIP-TF
  branch: main
dataDisplay:
  textFormat: text-orig-full
  browseNavLevel: 2
  exampleSection: abil0001
  browseContentPretty: false
  noneValues:
    - unknown
    - null
typeDisplay:
  inscription:
    label: "{inscription_id}"
    level: 3
  textpart:
    label: "{section_part}"
    level: 2
  line:
    label: "{line_n}"
    level: 1
    condense: true
    verselike: true
  word:
    features: "lang token_kind"
  markup:
    hidden: true
    features: "kind reason cert"
  entity:
    hidden: true
    features: "kind ref"
